// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:82525e1e-f79c-4e9a-8d77-d50425382e51',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ravenousapp-hosting-mobilehub-1718311255',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd11yd8sddndv9g.cloudfront.net',
    'aws_mobile_analytics_app_id': 'd7065f8960f94220a0b9cbf879ce547c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'cc731f11-7cbe-470e-b451-78d538762e13',
    'aws_project_name': 'Ravenous App',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'ravenousapp-mobilehub-1718311255',
}

export default awsmobile;
